import fs from 'fs';

// Sample movie titles, summaries, and release years
const movieTitles = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Inception",
    "Forrest Gump",
    "The Matrix",
    "Gladiator",
    "The Avengers",
    "The Lion King",
    "Titanic",
    "The Silence of the Lambs",
    "Pulp Fiction",
    "The Lord of the Rings: The Return of the King",
    "The Empire Strikes Back",
    "Interstellar",
    "Fight Club",
    "The Social Network",
    "The Departed",
    "Schindler's List",
    "Star Wars: A New Hope",
    "The Godfather: Part II",
    "The Shawshank Redemption2",
    "The Godfather2",
    "The Dark Knight2",
    "Inception2",
    "Forrest Gump2",
    "The Matrix2",
    "Gladiator2",
    "The Avengers2",
    "The Lion King2",
    "Titanic2",
    "The Silence of the Lambs2",
    "Pulp Fiction2",
    "The Lord of the Rings: The Return of the King2",
    "The Empire Strikes Back2",
    "Interstellar2",
    "Fight Club2",
    "The Social Network2",
    "The Departed2",
    "Schindler's List2",
    "Star Wars: A New Hope2",
    "The Godfather: Part II2",
    "The Shawshank Redemption3",
    "The Godfather3",
    "The Dark Knight3",
    "Inception3",
    "Forrest Gump3",
    "The Matrix3",
    "Gladiator3",
    "The Avengers3",
    "The Lion King3",
    "Titanic3",
    "The Silence of the Lambs3",
    "Pulp Fiction3",
    "The Lord of the Rings: The Return of the King3",
    "The Empire Strikes Back3",
    "Interstellar3",
    "Fight Club3",
    "The Social Network3",
    "The Departed3",
    "Schindler's List3",
    "Star Wars: A New Hope3",
    "The Godfather: Part II3",  
    "The Shawshank Redemption4",
    "The Godfather4",
    "The Dark Knight4",
    "Inception4",
    "Forrest Gump4",
    "The Matrix4",
    "Gladiator4",
    "The Avengers4",
    "The Lion King4",
    "Titanic4",
    "The Silence of the Lambs4",
    "Pulp Fiction4",
    "The Lord of the Rings: The Return of the King4",
    "The Empire Strikes Back4",
    "Interstellar4",
    "Fight Club4",
    "The Social Network4",
    "The Departed4",
    "Schindler's List4",
    "Star Wars: A New Hope4",
    "The Godfather: Part II4",

    "The Shawshank Redemption4",
    "The Godfather4",
    "The Dark Knight4",
    "Inception4",
    "Forrest Gump4",
    "The Matrix4",
    "Gladiator4",
    "The Avengers4",
    "The Lion King4",
    "Titanic4",
    "The Silence of the Lambs4",
    "Pulp Fiction4",
    "The Lord of the Rings: The Return of the King4",
    "The Empire Strikes Back4",
    "Interstellar4",
    "Fight Club4",
    "The Social Network4",
    "The Departed4",
    "Schindler's List4",
    "Star Wars: A New Hope4",
    "The Godfather: Part II4",

    "The Shawshank Redemption5",
    "The Godfather5",
    "The Dark Knight5",
    "Inception5",
    "Forrest Gump5",
    "The Matrix5",
    "Gladiator5",
    "The Avengers5",
    "The Lion King5",
    "Titanic5",
    "The Silence of the Lambs5",
    "Pulp Fiction5",
    "The Lord of the Rings: The Return of the King5",
    "The Empire Strikes Back5",
    "Interstellar5",
    "Fight Club5",
    "The Social Network5",
    "The Departed5",
    "Schindler's List5",
    "Star Wars: A New Hope5",
    "The Godfather: Part II5",

    "The Shawshank Redemption6",
    "The Godfather6",
    "The Dark Knight6",
    "Inception6",
    "Forrest Gump6",
    "The Matrix6",
    "Gladiator6",
    "The Avengers6",
    "The Lion King6",
    "Titanic6",
    "The Silence of the Lambs6",
    "Pulp Fiction6",
    "The Lord of the Rings: The Return of the King6",
    "The Empire Strikes Back6",
    "Interstellar6",
    "Fight Club6",
    "The Social Network6",
    "The Departed6",
    "Schindler's List6",
    "Star Wars: A New Hope6",
    "The Godfather: Part II6",
    "The Shawshank Redemption7",
    "The Godfather7",
    "The Dark Knight7",
    "Inception7",
    "Forrest Gump7",
    "The Matrix7",
    "Gladiator7",
    "The Avengers7",
    "The Lion King7",
    "Titanic7",
    "The Silence of the Lambs7",
    "Pulp Fiction7",
    "The Lord of the Rings: The Return of the King7",
    "The Empire Strikes Back7",
    "Interstellar7",
    "Fight Club7",
    "The Social Network7",
    "The Departed7",
    "Schindler's List7",
    "Star Wars: A New Hope7",
    "The Godfather: Part II7", 
];

const summaries = [
    "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
    "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
    "The presidencies of Kennedy and Johnson, the Vietnam War, the civil rights movement, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary name, Forrest Gump.",
    "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    "A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    "A young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
    "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    "A young FBI cadet must confide in an incarcerated and manipulative cannibal killer to receive his help on catching another serial killer who skins his victims.",
    "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "The hobbit, Frodo Baggins, and eight companions set out on a quest to destroy the powerful One Ring and bring an end to Sauron's reign of terror.",
    "The rebels join forces with the fleet of the Empire to overthrow the evil forces of the Sith and bring peace to the galaxy.",
    "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "An insomniac office worker forms an underground fight club with soap salesman Tyler Durden.",
    "Mark Zuckerberg creates the social networking site that would become known as Facebook, but the creation of Facebook comes at a price.",
    "A former cop turned private detective is hired to investigate the disappearance of a high-profile woman in Boston.",
    "The story of the Holocaust, focusing on the efforts of a German businessman to save the lives of over a thousand Polish Jews during World War II.",
    "A group of rebels seek to destroy the Death Star, a space station with enough power to destroy an entire planet.",
    "The continuation of Michael Corleone's saga of trying to establish a new criminal empire while grappling with betrayal.",
];

// Generate random release years between 1950 and 2020
function randomDateRelease() {
    const year = Math.floor(Math.random() * (2020 - 1950 + 1)) + 1950;
    const month = String(Math.floor(Math.random() * 12) + 1).padStart(2, "0");
    const day = String(Math.floor(Math.random() * 28) + 1).padStart(2, "0"); // To ensure valid day
    return `${year}-${month}-${day}`;
}

const imageURLs = [
    "https://graphicdesignjunction.com/wp-content/uploads/2012/05/large/movie-poster-20.jpg",
    "https://www.slashfilm.com/wp/wp-content/images/2017-bestposter-thorragnarok.jpg",
    "https://images2.fanpop.com/images/photos/8400000/Movie-Posters-movies-8405245-1224-1773.jpg",
    "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/61da8438155793.57575971afe13.jpg",
    "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/868e2d38155793.57575971b116a.jpg",
    "https://wallpapercave.com/wp/wp10941904.jpg",
    "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/e22ff753131197.596c4c560ae3b.jpg",
    "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/c358f738155793.57575971b1c09.jpg",
    "https://www.slashfilm.com/wp/wp-content/images/2017-bestposter-justiceleague.jpg",
    "https://wallpapercave.com/wp/wp7490940.jpg",
    "https://wallpapercave.com/wp/wp1945933.jpg",
]

const revenues = [
    10,
    5,
    150,
    200,
    250,
    325,
    400,
    425,
    450,
    475,
    480,
    490,
    800,
    1000,
    1400,
    1800,
    2000,
    3000,
    4000,
    6000,
    8000,
    10000,
    13000,
    15000,
    20000,
    23000,
    25000,
    28000,
    30000,
    100000,
    200000,
    500000,
    1000000,
    3000000,
    5000000
]

// Generate 200 movie objects
const movies = [];
for (let i = 0; i < 200; i++) {
    const movie = {
        title: movieTitles[Math.floor(Math.random() * movieTitles.length)],
        summary: summaries[Math.floor(Math.random() * summaries.length)],
        dateRelease: randomDateRelease(),
        image: imageURLs[Math.floor(Math.random() * imageURLs.length)],
        revenue: revenues[Math.floor(Math.random() * revenues.length)]
    };
    movies.push(movie);
}

// Output the generated movies (or you can store them to a file)
//console.log(movies); // Show first 5 items as a sample for verification

fs.writeFile('dummyData/movies.json', JSON.stringify(movies, null, 2), (err) => {
    if (err) {
        console.error('Error writing to file:', err);
    } else {
        console.log('Movies data has been written to dummyData/movies.json');
    }
});